version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: arabic_assessment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  # Changed from 5432 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Changed from 6379 to 6380
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/arabic_assessment
      - REDIS_URL=redis://redis:6379/0  # Internal Docker network still uses 6379
      - FLASK_ENV=development
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./audio_cache:/app/audio_cache

volumes:
  postgres_data:
  redis_data:
